{
 "title": "Bandwidth Usage",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Incoming & Outgoing Bandwidth Usage per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.bandwidth.bytesReceived)"
    },
    {
     "target": "aliasByMetric(stats.bandwidth.bytesSent)"
    }
   ]
  },
  {
   "title": "Total Bandwidth Used Since Last Restart",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.bandwidth.totalBytesReceived)"
    },
    {
     "target": "aliasByMetric(stats.gauges.bandwidth.totalBytesSent)"
    }
   ]
  },
  {
   "title": "Incoming Bandwidth Usage by Message",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.bandwidth.message.*.bytesReceived, 3)"
    }
   ]
  },
  {
   "title": "Outgoing Bandwidth Usage by Message",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.bandwidth.message.*.bytesSent, 3)"
    }
   ]
  },
  {
   "title": "Total Incoming Bandwidth Usage by Message (currently connected peers)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.bandwidth.message.*.totalBytesReceived, 4)"
    }
   ]
  },
  {
   "title": "Total Outgoing Bandwidth Usage by Message (currently connected peers)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.bandwidth.message.*.totalBytesSent, 4)"
    }
   ]
  },
  {
   "title": "95th Percentile Bandwidth Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowPercentile(sumSeries(stats.bandwidth.*), 95), 'Top 5% Bandwidth Spikes')"
    }
   ]
  }
 ]
}