{
 "title": "Memory Pool",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Mempool Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.transactions.mempool.totalTxBytes)"
    },
    {
     "target": "aliasByMetric(stats.gauges.transactions.mempool.totalTransactions)"
    }
   ]
  },
  {
   "title": "Mempool Dynamic Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.transactions.mempool.memoryUsageBytes)"
    }
   ]
  },
  {
   "title": "Minimum Mempool Transaction Fee",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Satoshis Per KiloByte" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.transactions.mempool.minFeePerKb)"
    }
   ]
  }
 ]
}