{
 "title": "Peers",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10m",
 "panels": [
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Peers" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.peers.fullNodeConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.spvNodeConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.inboundConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.outboundConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.knownAddresses)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.ipv4Connections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.ipv6Connections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.torConnections)"
    },
    {
     "target": "aliasByMetric(stats.gauges.peers.totalConnections)"
    }
   ]
  },
  {
   "title": "Peer Pings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs", "label": "Ping Time" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.timers.peers.ping_us.lower)"
    },
    {
     "target": "aliasByMetric(stats.timers.peers.ping_us.median)"
    },
    {
     "target": "aliasByMetric(stats.timers.peers.ping_us.upper)"
    }
   ]
  },
  {
   "title": "Peer Misbehavior",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Rejected Messages per sec" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.message.sent.reject*)"
    },
    {
     "target": "aliasByMetric(stats.misbehavior.banned)"
    }
   ]
  }
 ]
}