{
 "title": "Transactions",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Transaction Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Transaction outputs" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.transactions.txCacheSize)"
    },
    {
     "target": "alias(stats.gauges.transactions.mempool.totalTransactions, 'txesInMempool')"
    },
    {
     "target": "aliasByMetric(stats.gauges.transactions.orphans)"
    }
   ]
  },
  {
   "title": "Transactions Accepted Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.transactions.accepted, 'txAccepted')"
    },
    {
     "target": "alias(stats.gauges.transactions.txRate, 'TX/S trailing month average')"
    }
   ]
  },
  {
   "title": "Transactions Accepted vs Rejected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "aliasByMetric(stats.message.received.tx)"
    },
    {
     "refCount": -1,
     "target": "aliasByMetric(stats.message.received.dstx)"
    },
    {
     "refCount": -1,
     "target": "alias(stats.transactions.accepted, 'txAccepted')"
    },
    {
     "target": "alias(diffSeries(sumSeries(#B, #C), #A), 'txMessagesRejected')",
     "targetFull": "alias(diffSeries(sumSeries(aliasByMetric(stats.message.received.tx), aliasByMetric(stats.message.received.dstx)), alias(stats.transactions.accepted, 'txAccepted')), 'txMessagesRejected')"
    }
   ]
  },
  {
   "title": "DASH Spent Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scale(stats.transactions.inputValue, 1e-8), 'DASH')"
    }
   ]
  },
  {
   "title": "% Transaction Inputs vs Outputs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.transactions.inputs)"
    },
    {
     "target": "aliasByMetric(stats.transactions.outputs)"
    }
   ]
  },
  {
   "title": "Bytes Per Transaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(stats.transactions.sizeBytes, #B), 'Total TX bytes / # TX')",
     "targetFull": "alias(divideSeries(stats.transactions.sizeBytes, stats.transactions.accepted), 'Total TX bytes / # TX')"
    }
   ]
  },
  {
   "title": "Signature Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.transactions.sigOps)"
    }
   ]
  },
  {
   "title": "Total Historical Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.transactions.totalTransactions"
    }
   ]
  }
 ]
}