{
 "title": "Unspent Transaction Output Set",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10m",
 "panels": [
  {
   "title": "Total Transactions With Unspent Outputs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.utxoset.tx)"
    }
   ]
  },
  {
   "title": "Unspent Transaction Outputs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Unspent Transaction Outputs" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.utxoset.txOutputs)"
    }
   ]
  },
  {
   "title": "Size of Serialized UTXO Set",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.utxoset.dbSizeBytes)"
    }
   ]
  },
  {
   "title": "Total Coins in Existence",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.utxoset.totalAmount)"
    }
   ]
  }
 ]
}